backend:
  name: github
  repo: Georgegriff/cgguitar-site # Path to your GitHub repository
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
publish_mode: editorial_workflow
local_backend: true
media_folder: "src/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About page"
        name: "about"
        file: "src/about/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - 
            label: Hero Section
            name: hero
            widget: object
            collapsed: true
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: Description
                name: description
                required: false
                widget: string
              -
                label: Subtitle
                name: subtitle
                required: false
                widget: string
              -
                label: Image
                name: image
                widget: object
                fields:
                  - label: Source
                    name: src
                    widget: image
                  - label: Description
                    name: alt
                    widget: string
              - 
                label: Call To Action
                required: false
                name: callToAction
                max: 2
                widget: "list"
                fields:
                  -
                    name: type
                    label: Type
                    widget: select
                    default: ["primary"]
                    options: ["primary", "secondary"]
                  -
                    name: text
                    label: Text
                    widget: string
                  -
                    name: link
                    label: Link
                    widget: string
          -
            label: "Sections"
            name: "components"
            widget: "list"
            allow_add: true
            collapsed: false
            types:
              - label: 'Card'
                widget: 'object'
                name: 'card'
                fields:
                  - widget: "relation"
                    collapsed: false
                    multiple: false
                    name: 'component'
                    collection: "components"
                    search_fields: ["label"]
                    value_field: "name"
                    display_fields: ["label"]
  - name: "card"
    label: "Cards"
    folder: src/components/cards
    slug: "{{name}}.md"
    fields:
      - { label: Label, name: label, widget: string}
      - { label: Name, name: name, widget: string}
      - { label: Extends, name: extends, widget: relation, required: false,
              collapsed: false,
              multiple: false,
              collection: "card",
              search_fields: ["label"],
              value_field: "name",
              display_fields: ["label"],
        }
      - { required: false, label: Heading, name: heading, widget: string}
      - { required: false, label: Image position, name: direction, widget: 'select', default: 'normal', options: ["normal", "reverse"] }
      - { required: false, label: Body, name: "body", widget: 'markdown' }
      - { required: false, "label": "Image", "name": "image", "widget": "object", "fields": [
        {
          required: false,
          "label": "Source",
          "name": "src",
          "widget": "image"
        },
        {
          required: false,
          "label": "Description",
          "name": "alt",
          "widget": "string"
        }
        ]
      }
      - { required: false, "label": "Link", "name": "link", "widget": "object", "fields": [
        {
          "label": "Url",
          "name": "url",
          "widget": "string",
          required: false
        },
        {
          "label": "Text",
          "name": "text",
          "widget": "string",
          required: false
        }
        ]
      }
  - name: "testimonial"
    label: "Testimonials"
    create: true # Allow users to create new documents in this collection
    folder: src/testimonials
    slug: "{{name}}.md" # Filename template
    fields:
      - { label: Name, name: name, widget: string}
      - { label: Date, name: date, widget: date}
      - { label: Image, name: image, widget: image, required: false }
      - {label: "Body", name: "body", widget: "markdown"}
