backend:
  name: github
  repo: Georgegriff/cgguitar-site # Path to your GitHub repository
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
publish_mode: editorial_workflow
local_backend: true
media_folder: "src/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home page"
        name: "home"
        file: "src/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - 
            label: Hero Section
            name: hero
            widget: object
            collapsed: true
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: Description
                name: description
                required: false
                widget: string
              -
                label: Subtitle
                name: subtitle
                required: false
                widget: string
              -
                label: Image
                name: image
                widget: object
                fields:
                  - label: Source
                    name: src
                    widget: image
                  - label: Description
                    name: alt
                    widget: string
              - 
                label: Call To Action
                required: false
                name: callToAction
                max: 2
                widget: "list"
                fields:
                  -
                    name: type
                    label: Type
                    widget: select
                    default: ["primary"]
                    options: ["primary", "secondary"]
                  -
                    name: text
                    label: Text
                    widget: string
                  -
                    name: link
                    label: Link
                    widget: string
          -
            label: "Sections"
            name: "components"
            widget: "list"
            allow_add: true
            collapsed: true
            types:
              - label: 'Card'
                widget: 'object'
                name: 'card'
                summary: 'card: {{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "card"
                    search_fields: ["label"]
                    value_field: "name"
                    display_fields: ["label"]
              - label: 'Quote'
                widget: 'object'
                name: 'quote'
                summary: 'quote: {{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "quote"
                    search_fields: ["label"]
                    value_field: "name"
                    display_fields: ["label"]
              - label: 'Playlist'
                widget: 'object'
                name: 'playlist'
                summary: 'playlist: {{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "playlist"
                    search_fields: ["title"]
                    value_field: "name"
                    display_fields: ["title"]
              - label: 'Testimonial'
                widget: 'object'
                name: 'testimonial'
                summary: 'testimonial: {{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "testimonial"
                    search_fields: ["name"]
                    value_field: "name"
                    display_fields: ["name"]
              - label: 'Slogan'
                widget: 'object'
                name: 'slogan'
                summary: '{{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "slogan"
                    search_fields: ["name"]
                    value_field: "name"
                    display_fields: ["name"]
              - label: 'Levels'
                widget: 'object'
                name: 'levels'
                summary: '{{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "levels"
                    search_fields: ["name"]
                    value_field: "name"
                    display_fields: ["name"]
              - label: 'Media Cards'
                widget: 'object'
                name: 'gridCard'
                summary: '{{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "gridCard"
                    search_fields: ["name"]
                    value_field: "name"
                    display_fields: ["name"]
      - label: "About page"
        name: "about"
        file: "src/about/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - 
            label: Hero Section
            name: hero
            widget: object
            collapsed: true
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: Description
                name: description
                required: false
                widget: string
              -
                label: Subtitle
                name: subtitle
                required: false
                widget: string
              -
                label: Image
                name: image
                widget: object
                fields:
                  - label: Source
                    name: src
                    widget: image
                  - label: Description
                    name: alt
                    widget: string
              - 
                label: Call To Action
                required: false
                name: callToAction
                max: 2
                widget: "list"
                fields:
                  -
                    name: type
                    label: Type
                    widget: select
                    default: ["primary"]
                    options: ["primary", "secondary"]
                  -
                    name: text
                    label: Text
                    widget: string
                  -
                    name: link
                    label: Link
                    widget: string
          -
            label: "Sections"
            name: "components"
            widget: "list"
            allow_add: true
            collapsed: true
            types:
              - label: 'Card'
                widget: 'object'
                name: 'card'
                summary: 'card: {{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "card"
                    search_fields: ["label"]
                    value_field: "name"
                    display_fields: ["label"]
              - label: 'Quote'
                widget: 'object'
                name: 'quote'
                summary: 'quote: {{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "quote"
                    search_fields: ["label"]
                    value_field: "name"
                    display_fields: ["label"]
              - label: 'Playlist'
                widget: 'object'
                name: 'playlist'
                summary: 'playlist: {{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "playlist"
                    search_fields: ["title"]
                    value_field: "name"
                    display_fields: ["title"]
              - label: 'Testimonial'
                widget: 'object'
                name: 'testimonial'
                summary: 'testimonial: {{fields.name}}'
                fields:
                  - widget: "relation"
                    name: 'name'
                    collection: "testimonial"
                    search_fields: ["name"]
                    value_field: "name"
                    display_fields: ["name"]
  - name: "card"
    label: "Card"
    folder: src/components/cards
    slug: "{{name}}"
    create: true
    fields:
      - { required: false, label: Label, name: label, widget: string}
      - { label: Name, name: name, widget: string, hint: "Don't change name once created"}
      - { label: Type, name: type, widget: hidden, default: 'card'}
      - { required: false, label: Heading, name: heading, widget: string}
      - { required: false, label: Body, name: "body", widget: 'markdown' }
      - { required: false, label: Image position, name: direction, widget: 'select', default: 'normal', options: ["normal", "reverse"] }
      - { required: false, "label": "Image", "name": "image", "widget": "object", "fields": [
        {
          required: false,
          "label": "Source",
          "name": "src",
          "widget": "image"
        },
        {
          required: false,
          "label": "Description",
          "name": "alt",
          "widget": "string"
        }
        ]
      }
      - { required: false, "label": "Link", "name": "link", "widget": "object", "fields": [
        {
          "label": "Url",
          "name": "url",
          "widget": "string",
          required: false
        },
        {
          "label": "Text",
          "name": "text",
          "widget": "string",
          required: false
        }
        ]
      }
  - name: "quote"
    label: "Quote"
    folder: src/components/quote
    slug: "{{name}}"
    create: true
    fields:
      - { label: Label, name: label, widget: string}
      - { label: Type, name: type, widget: hidden, default: 'quote'}
      - { label: Name, name: name, widget: string, hint: "Don't change name once created"}
      - { label: Body, name: body, widget: markdown}
  - name: "testimonial"
    label: "Testimonial"
    create: true # Allow users to create new documents in this collection
    folder: src/testimonials
    slug: "{{name}}" # Filename template
    fields:
      - { label: Name, name: name, widget: string, hint: "Don't change name once created"}
      - { label: Date, name: date, widget: date}
      - { label: Image, name: image, widget: image, required: false, media_folder: "/src/images/testimonials", public_folder: "/images/testimonials" }
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "playlist"
    label: "Playlist"
    folder: src/playlists
    slug: "{{name}}"
    create: true
    fields:
      - { label: Title, name: title, widget: string}
      - { label: Name, name: name, widget: string, hint: "Don't change name once created"}
      - { label: Playlist ID, name: id, widget: string}
      - { label: Description, name: description, widget: markdown, required: false}
  - name: "slogan"
    label: "Slogan"
    create: false
    files:
      - label: "Slogan"
        file: "src/components/slogan.md"
        name: "slogan"
        fields:
          - { label: Name, name: name, widget: string, hint: "Don't change name once created"}
          - { label: Items, name: items, widget: list,
              fields: [
                { label: "Title", "name": "title", "widget": "string"},
                { label: "Text", "name": "text", "widget": "string"}
              ]
          }
  - name: "levels"
    label: "Levels"
    create: false
    files:
      - label: "Levels"
        file: "src/lessons/levels/index.md"
        name: "levels"
        fields:
          - { label: Name, name: name, widget: string, hint: "Don't change name once created"}
          - { label: Levels, name: items, widget: list, max: 3,
            fields: [
              { label: Name, name: name, widget: string, hint: "Don't change name once created" },
              { label: Description, name: description, widget: string },
              { label: Image, name: image, widget: image },
              { required: false, label: Link, name: link, widget: "boolean", default: false },
              { label: Quote, name: quote, widget: "markdown" }
              ]
          }
  - name: "gridCard"
    label: "Media Cards"
    create: true
    folder: "src/components/grid-cards"
    slug: "{{name}}"
    fields:
      - { label: Title, name: title, widget: string}
      - { label: Class, name: class, widget: string, required: false}
      - { label: Name, name: name, widget: string, hint: "Don't change name once created"}
      - { required: false, label: Icons, name: icons, widget: list, max: 4,
        fields: [
          { label: Text, name: text, widget: string },
          { label: Image, name: image, widget: image },
        ]
      }
      - { required: false, label: Video, name: video, widget: "object",
        fields: [
          {required: false, label: "Channel ID", name: "channel"},
          {required: false,label: "Video ID", name: "id",},
          {required: false,label: "link", name: "link", "widget": "object", "fields": [
            {required: false, label: "Text", name: "text"},
            {required: false,label: "Url", name: "url",},
            ]},
        ]
      }