backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
publish_mode: editorial_workflow

media_folder: "src/images" # Media files will be stored in the repo under images/uploads
media_folder: "/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "testimonial"
    label: "Testimonial"
    create: true # Allow users to create new documents in this collection
    folder: src/testimonials
    slug: "{{slug}}/index.md" # Filename template
    fields:
      - { label: Name, name: name, widget: string, required: true}
      - { label: Image, name: image, widget: image}
        - {label: "Body", name: "body", widget: "markdown"}
