backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "src/images" # Media files will be stored in the repo under images/uploads
media_folder: "/images" # Media files will be stored in the repo under images/uploads