# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 1500 daily
    - cron: '00 15 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/602d2c19cbd4581bd8439cc7