name: Pull Request on Branch Push
on:
  push:
    branches-ignore:
      - main
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "cms-draft"
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_UPDATE: true
          PULL_REQUEST_REVIEWERS: "Georgegriff"
          PULL_REQUEST_TITLE: "CG Guitar website content"